config/routes.rb
Pingpong::Application.routes.draw do
  resources :players

  resources :games

  root :to => "players#index"

end

app/models/game.rb
require 'elo'

class Game < ActiveRecord::Base
  belongs_to :player_one, :class_name => "Player"
  belongs_to :player_two, :class_name => "Player"

  # Every time a result is set, it tells the Elo::Player
	# objects to update their scores.
  def process_result(new_result)
    self.result = new_result
    calculate
  end

  def calculate
    if self.result
      player_one.send(:played, self)
      player_two.send(:played, self)
      save
    end
    self
  end

	# Player +:one+ has won!
	# This is a shortcut method for setting the score to 1
  def win
    process_result 1.0
  end

	# Player +:one+ has lost!
	# This is a shortcut method for setting the score to 0
  def lose
    process_result 0.0
  end

	# It was a draw.
	# This is a shortcut method for setting the score to 0.5
  def draw
    process_result 0.5
  end


	# Set the winner. Provide it with a Elo::Player. 
  def winner=(player)
    process_result(player == player_one ? 1.0 : 0.0)
  end

	# Set the loser. Provide it with a Elo::Player. 
  def loser=(player)
    process_result(player == player_one ? 0.0 : 1.0)
  end

	# Access the Elo::Rating objects for both players.
  def ratings
    @ratings ||= { player_one => rating_one, player_two => rating_two }
  end


  private

	# Create an Elo::Rating object for player one
  def rating_one
    Elo::Rating.new(:result        => self.result,
               :old_rating    => player_one.rating,
               :other_rating  => player_two.rating,
               :k_factor      => player_one.k_factor)
  end

	# Create an Elo::Rating object for player two
  def rating_two
    Elo::Rating.new(:result        => (1.0 - self.result),
               :old_rating    => player_two.rating,
               :other_rating  => player_one.rating,
               :k_factor      => player_two.k_factor)
  end
  
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :check_password, :only => [:create, :update, :destroy]
  
  
  # GET /games
  # GET /games.xml
  def index
    @games = Game.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
    end
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.xml
  def create
    @game = Game.new(params[:game])
    @game.calculate
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to(@game, :notice => 'Game was successfully created.') }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(@game, :notice => 'Game was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end
  
  
  # Very very simple password check
  protected    
  def check_password
    puts config.master_password
    if params[:password] != APP_CONFIG['master_password']
      render :text =>  "Don't do that!"
      return
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_one_id %><br />
		<%= f.select(:player_one_id, Player.all.collect {|p| [ p.name, p.id ] }) %> 
		<input type="radio" name="game[result]" value="1.0"> Winner
  </div>
  <div class="field">
    <%= f.label :player_two_id %><br />
    <%= f.select(:player_two_id, Player.all.collect {|p| [ p.name, p.id ] }) %>
		<input type="radio" name="game[result]" value="0"> Winner
  </div>
	<div class="field">
    Master H4CK Password<br />
    <input type="password" name="password">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="grid_8 prefix_2">
	<h1>Editing game</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @game %> |
	<%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div id="last_matches" class="grid_8 prefix_2 suffix_2">
	<div class="header"></div>
	
	<% @games.each_with_index do |game, index| %>
		<div class="match" title="Played: <%= game.created_at %>">
			<div class="versus">&nbsp;</div>
			
			<% if game.result > 0.5 %>
			<div class="grid_4 alpha game_player">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 alpha game_player loser">
			<% end %>
				<div class="grid_1 avatar alpha"><img src="<%= game.player_one.avatar %>" height="60"/></div>
				<div class="grid_3 name omega"><%= link_to "@"+game.player_one.name, game.player_one %></div>
			</div>


			<% if game.result < 0.5 %>
			<div class="grid_4 omega game_player two">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 omega game_player two loser">
			<% end %>
				<div class="grid_3 name alpha"><%= link_to "@"+game.player_two.name, game.player_two %></div>
				<div class="grid_1 avatar omega"><img src="<%= game.player_two.avatar %>" height="60"/></div>
			</div>
			
		</div>
	<% end %>


</div>

app/views/games/new.html.erb
<div class="grid_8 prefix_2">
	<h1>New game</h1>

	<%= render 'form' %>

	<%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Result:</b>
  <%= @game.result %>
</p>

<p>
  <b>Player one:</b>
  <%= @game.player_one_id %>
</p>

<p>
  <b>Player two:</b>
  <%= @game.player_two_id %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>