config/routes.rb
Pingpong::Application.routes.draw do
  resources :players

  resources :games

  root :to => "players#index"

end

app/models/player.rb
require 'elo'

class Player < ActiveRecord::Base
  
  has_many :games, :finder_sql => 'SELECT * FROM games WHERE (games.player_one_id = #{self.id} OR games.player_two_id = #{self.id})'
  
  has_many :victories, :class_name => 'Game', 
            :finder_sql => 'SELECT * FROM games WHERE ((games.player_one_id = #{self.id} AND result >= 1) OR 
                                                      (games.player_two_id = #{self.id} AND result = 0))'
                                                      
  has_many :defeats, :class_name => 'Game', 
            :finder_sql => 'SELECT * FROM games WHERE ((games.player_one_id = #{self.id} AND result = 0) OR 
                                                      (games.player_two_id = #{self.id} AND result >= 1))'
  
  # The rating you provided, or the default rating from configuration
  # def rating
  #   @rating ||= Elo.config.default_rating
  # end

	# The number of games played is needed for calculating the K-factor.
  def games_played
    @games_played ||= games.size
  end
  
  # Is the player considered a pro, because his/her rating crossed
	# the threshold configured? This is needed for calculating the K-factor.
  def pro_rating?
    self.rating >= Elo.config.pro_rating_boundry
  end
  
  # Is the player just starting? Provide the boundry for
	# the amount of games played in the configuration.
	# This is needed for calculating the K-factor.
  def starter?
    games_played < Elo.config.starter_boundry
  end

	# FIDE regulations specify that once you reach a pro status
	# (see +pro_rating?+), you are considered a pro for life.
	#
	# You might need to specify it manually, when depending on
	# external persistence of players.
	#
	#		Elo::Player.new(:pro => true)
  def pro?
    !!@pro
  end
  
  
  # Calculates the K-factor for the player.
	# Elo allows you specify custom Rules (see Elo::Configuration).
	#
	# You can set it manually, if you wish:
	#
	#		Elo::Player.new(:k_factor => 10)
	#
	#	This stops this player from using the K-factor rules.
  def k_factor
    return @k_factor if @k_factor
    Elo.config.applied_k_factors.each do |rule|
      return rule[:factor] if instance_eval(&rule[:rule])
    end
    Elo.config.default_k_factor
  end
  
  
  # Start a game with another player. At this point, no
	# result is known and nothing really happens.
  def versus(other_player, options = {})
    Game.new(options.merge(:player_one => self, :player_two => other_player)).calculate
  end

	# Start a game with another player and set the score
	# immediately.
  def wins_from(other_player, options = {})
    versus(other_player, options).win
  end

	# Start a game with another player and set the score
	# immediately.
  def plays_draw(other_player, options = {})
    versus(other_player, options).draw
  end

	# Start a game with another player and set the score
	# immediately.
  def loses_from(other_player, options = {})
    versus(other_player, options).lose
  end
  
  
  private

  # A Game tells the players informed to update their
  # scores, after it knows the result (so it can calculate the rating).
  #
  # This method is private, because it is called automatically.
  # Therefore it is not part of the public API of Elo.
  def played(game)
    games << game
    self.rating = game.ratings[self].new_rating
    @pro    = true if pro_rating?
    save
  end
  
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :check_password, :only => [:create, :update, :destroy]
  
  
  # GET /players
  # GET /players.xml
  def index
    @players = Player.order('rating DESC')
    @games = Game.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @players }
    end
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to(@player, :notice => 'Player was successfully created.') }
        format.xml  { render :xml => @player, :status => :created, :location => @player }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url) }
      format.xml  { head :ok }
    end
  end
  
  
  # Very very simple password check
  protected    
  def check_password
    if params[:password] !=  APP_CONFIG['master_password']
      render :text =>  "Don't do that!"
      return
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    Master H4CK Password<br />
    <input type="password" name="password">
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<div id="ranking" class="grid_8 prefix_2 suffix_2">
	<div class="header"></div>
	
	<% @players.each_with_index do |player, index| %>
		<% if index != 0 %>
			<div class="line grid_8"></div>
		<% end %>
		<div class="player">
			<div class="grid_1 alpha"><div class="rank rank_<%= index+1 %>"></div></div>
			<div class="grid_1 avatar"><img src="<%= player.avatar %>" height="60" title="Points: <%= player.rating %> "/></div>
			<div class="grid_4 name" title="Points: <%= player.rating %> "><%= link_to "@"+player.name, player %></div>
			<div class="grid_2 omega stats">
				matches: <%= player.games.size %><br/>
				victories: <%= player.victories.size %><br/>
				defeats: <%= player.defeats.size %>
			</div>
		</div>
	<% end %>

</div>



<div id="last_matches" class="grid_8 prefix_2 suffix_2">
	<div class="header"></div>
	
	<% @games.each_with_index do |game, index| %>
		<div class="match" title="Played: <%= game.created_at %>">
			<div class="versus">&nbsp;</div>
			
			<% if game.result > 0.5 %>
			<div class="grid_4 alpha game_player">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 alpha game_player loser">
			<% end %>
				<div class="grid_1 avatar alpha"><img src="<%= game.player_one.avatar %>" height="60"/></div>
				<div class="grid_3 name omega"><%= link_to "@"+game.player_one.name, game.player_one %></div>
			</div>


			<% if game.result < 0.5 %>
			<div class="grid_4 omega game_player two">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 omega game_player two loser">
			<% end %>
				<div class="grid_3 name alpha"><%= link_to "@"+game.player_two.name, game.player_two %></div>
				<div class="grid_1 avatar omega"><img src="<%= game.player_two.avatar %>" height="60"/></div>
			</div>
			
		</div>
	<% end %>


</div>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div id="player_stats" class="grid_6 prefix_3 suffix_3">
	<div class="header"></div>
	
	<div class="grid_1 avatar alpha"><img src="<%= @player.avatar %>" height="60"/></div>
	<div class="grid_5 name omega">@<%= @player.name %></div>
	
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load('visualization', '1', {packages: ['corechart']});
  </script>
  <script type="text/javascript">
    function drawVisualization() {
      // Create and populate the data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Matches');
      data.addColumn('number', 'Number');
      data.addRows(2);
      data.setValue(0, 0, 'Won');
      data.setValue(0, 1, <%=@player.victories.size%>);
      data.setValue(1, 0, 'Lost');
      data.setValue(1, 1, <%=@player.defeats.size%>);
    
      // Create and draw the visualization.
      new google.visualization.PieChart(document.getElementById('chart')).
          draw(data, {
						backgroundColor: 'transparent', 
						colors: ['#0A4F68', '#A01D13'],
						fontName: "Helvetica Neue",
						legend: 'none',
						title: 'Points: <%=@player.rating%>',
						titleTextStyle: {color: 'white', fontSize: 16, fontName: "Helvetica Neue"},
						height: 400,
						chartArea: {top: 40, width:"100%", height:"100%"}});
    }

    google.setOnLoadCallback(drawVisualization);
  </script>
	<div id="chart" ></div>
	
</div>


<div id="match_history" class="grid_8 prefix_2 suffix_2">
	<div class="header"></div>

	<% @player.games.each_with_index do |game, index| %>
		<div class="match" title="Played: <%= game.created_at %>">
			<div class="versus">&nbsp;</div>

			<% if game.result > 0.5 %>
			<div class="grid_4 alpha game_player">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 alpha game_player loser">
			<% end %>
				<div class="grid_1 avatar alpha"><img src="<%= game.player_one.avatar %>" height="60"/></div>
				<div class="grid_3 name omega"><%= "@"+game.player_one.name %></div>
			</div>


			<% if game.result < 0.5 %>
			<div class="grid_4 omega game_player two">
				<div class="winner">&nbsp;</div>
			<% else %>
			<div class="grid_4 omega game_player two loser">
			<% end %>
				<div class="grid_3 name alpha"><%= "@"+game.player_two.name %></div>
				<div class="grid_1 avatar omega"><img src="<%= game.player_two.avatar %>" height="60"/></div>
			</div>

		</div>
	<% end %>


</div>